apiVersion: v1
kind: Namespace
metadata:
  name: redis-ns-54
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy-54
  namespace: redis-ns-54
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
